import { useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { LuArrowRight, LuSparkles, LuTarget, LuBrain, LuTrendingUp, LuBookOpen, LuUsers, LuZap } from 'react-icons/lu';
import './Landing.css';

export default function Landing() {
  const vantaRef = useRef(null);
  const vantaEffect = useRef(null);

  useEffect(() => {
    // Initialize Vanta Globe
    const initVanta = () => {
      if (window.VANTA && vantaRef.current && !vantaEffect.current) {
        vantaEffect.current = window.VANTA.GLOBE({
          el: vantaRef.current,
          mouseControls: true,
          touchControls: true,
          gyroControls: false,
          minHeight: 200.00,
          minWidth: 200.00,
          scale: 1.00,
          scaleMobile: 1.00,
          color: 0xd43e48,
          color2: 0x1a1a2e,
          backgroundColor: 0x0a0a0f,
          size: 1.2,
        });
      }
    };

    // Try immediately, or wait for scripts to load
    if (window.VANTA) {
      initVanta();
    } else {
      const timer = setInterval(() => {
        if (window.VANTA) {
          initVanta();
          clearInterval(timer);
        }
      }, 200);

      return () => clearInterval(timer);
    }

    return () => {
      if (vantaEffect.current) {
        vantaEffect.current.destroy();
        vantaEffect.current = null;
      }
    };
  }, []);

  const features = [
    { icon: <LuTarget />, title: 'Adaptive Quizzes', desc: 'AI-driven difficulty adjustment that adapts to your skill level in real-time.' },
    { icon: <LuBrain />, title: 'AI-Powered Insights', desc: 'Get personalized explanations and custom study paths generated by AI.' },
    { icon: <LuTrendingUp />, title: 'Smart Analytics', desc: 'Detailed dashboards with performance trends and weak area detection.' },
    { icon: <LuBookOpen />, title: 'Curated Resources', desc: 'Hand-picked video, article, and practice recommendations for each topic.' },
    { icon: <LuUsers />, title: 'Educator Dashboard', desc: 'Class-wide heatmaps, per-student drill-down, and quiz management.' },
    { icon: <LuZap />, title: 'Gamification', desc: 'Earn XP, unlock badges, maintain streaks, and climb the leaderboard.' },
  ];

  return (
    <div className="landing">
      {/* Hero Section with Vanta Globe */}
      <section className="hero" ref={vantaRef}>
        <div className="hero-overlay"></div>
        
        <nav className="landing-nav">
          <div className="landing-nav-logo">
            <div className="logo-icon-landing">🧠</div>
            <span className="logo-text-landing">CodeManthan</span>
          </div>
          <div className="landing-nav-actions">
            <Link to="/login" className="btn btn-secondary" id="nav-login-btn">Sign In</Link>
            <Link to="/register" className="btn btn-primary" id="nav-register-btn">Get Started</Link>
          </div>
        </nav>

        <div className="hero-content animate-fadeInUp">
          <div className="hero-badge">
            <LuSparkles />
            <span>AI-Powered Personalized Learning</span>
          </div>
          <h1 className="hero-title">
            Learn Smarter,<br />
            <span className="hero-gradient-text">Not Harder</span>
          </h1>
          <p className="hero-subtitle">
            CodeManthan adapts to your unique learning style. Take adaptive quizzes, 
            discover your weak areas, and get AI-generated study paths — all in one platform.
          </p>
          <div className="hero-actions">
            <Link to="/register" className="btn btn-primary btn-lg" id="hero-get-started">
              Start Learning Free
              <LuArrowRight />
            </Link>
            <Link to="/login" className="btn btn-secondary btn-lg" id="hero-login">
              Sign In
            </Link>
          </div>

          <div className="hero-stats">
            <div className="hero-stat">
              <span className="hero-stat-value">80+</span>
              <span className="hero-stat-label">Quiz Questions</span>
            </div>
            <div className="hero-stat-divider"></div>
            <div className="hero-stat">
              <span className="hero-stat-value">4</span>
              <span className="hero-stat-label">Subjects</span>
            </div>
            <div className="hero-stat-divider"></div>
            <div className="hero-stat">
              <span className="hero-stat-value">AI</span>
              <span className="hero-stat-label">Powered</span>
            </div>
            <div className="hero-stat-divider"></div>
            <div className="hero-stat">
              <span className="hero-stat-value">∞</span>
              <span className="hero-stat-label">Adaptive</span>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="features-section" id="features">
        <div className="container">
          <div className="section-header animate-fadeInUp">
            <span className="section-badge">Features</span>
            <h2 className="section-title">Everything You Need to <span className="gradient-text">Excel</span></h2>
            <p className="section-subtitle">Our AI-driven platform combines adaptive testing, intelligent analytics, and personalized recommendations.</p>
          </div>

          <div className="features-grid">
            {features.map((feature, index) => (
              <div className="feature-card animate-fadeInUp" key={index} style={{ animationDelay: `${index * 0.1}s` }}>
                <div className="feature-icon">{feature.icon}</div>
                <h3 className="feature-title">{feature.title}</h3>
                <p className="feature-desc">{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="how-section">
        <div className="container">
          <div className="section-header">
            <span className="section-badge">How It Works</span>
            <h2 className="section-title">Three Steps to <span className="gradient-text">Mastery</span></h2>
          </div>
          <div className="steps-grid">
            <div className="step-card animate-fadeInUp delay-1">
              <div className="step-number">01</div>
              <h3>Choose Your Subject</h3>
              <p>Pick from Mathematics, Science, Computer Science, or English. Select your topic and difficulty.</p>
            </div>
            <div className="step-card animate-fadeInUp delay-2">
              <div className="step-number">02</div>
              <h3>Take Adaptive Quizzes</h3>
              <p>Our AI adjusts question difficulty in real-time based on your performance. Get instant feedback.</p>
            </div>
            <div className="step-card animate-fadeInUp delay-3">
              <div className="step-number">03</div>
              <h3>Get AI Recommendations</h3>
              <p>Receive personalized study paths, resource recommendations, and track your progress over time.</p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="cta-section">
        <div className="container">
          <div className="cta-card">
            <div className="cta-content">
              <h2>Ready to Transform Your Learning?</h2>
              <p>Join CodeManthan today and experience AI-powered personalized education.</p>
              <Link to="/register" className="btn btn-primary btn-lg" id="cta-register">
                Get Started Now <LuArrowRight />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <div className="container">
          <div className="footer-content">
            <div className="footer-brand">
              <div className="landing-nav-logo">
                <div className="logo-icon-landing">🧠</div>
                <span className="logo-text-landing">CodeManthan</span>
              </div>
              <p>AI-Powered Personalized Learning Pathways</p>
              <p className="footer-ps">PS0402 — Sponsored by RV TECHLEARN</p>
            </div>
            <div className="footer-links">
              <div>
                <h4>Platform</h4>
                <Link to="/register">Get Started</Link>
                <Link to="/login">Sign In</Link>
              </div>
              <div>
                <h4>Features</h4>
                <span>Adaptive Quizzes</span>
                <span>AI Insights</span>
                <span>Analytics</span>
              </div>
            </div>
          </div>
          <div className="footer-bottom">
            <p>© 2026 CodeManthan. Built for hackathon by Team CodeManthan.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
